---
language: python
services: docker

env:
  global:
    - ROLE_NAME: alfresco52
  matrix:
    # Test defaults.
    - MOLECULE_DISTRO: ubuntu1804

    # Test other role features.
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-http-port.yml

install:
 - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
