---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1804
    # image: ubuntu:18.04
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        alfresco_installer: alfresco-community-installer-201707-linux-x64.bin
        # vieja
        # alfresco_installer: alfresco-community-installer-201602-linux-x64.bin
        alf_glob_prop_path: >
          /opt/alfresco_community/tomcat/shared/classes/alfresco-global.properties
        alf_root: /opt/alfresco_community/
        dir_root: /opt/alfresco_community/alf_data
        solr4_root: /opt/alfresco_community/alf_data/solr4/index
        installer_delay: 190
        upgrade: false
        database: mysql
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
